In [1]:
#import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


In [56]:
#read in and explore the training/test dataset 
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [57]:
#a sample of the test dataset with 5 rows
test.sample(5)

PassengerId  Pclass                             Name     Sex   Age  \
117         1009       3  Sandstrom, Miss. Beatrice Irene  female   1.0   
303         1195       3                Pokrnic, Mr. Tome    male  24.0   
30           922       2     Louch, Mr. Charles Alexander    male  50.0   
202         1094       1           Astor, Col. John Jacob    male  47.0   
59           951       1      Chaudanson, Miss. Victorine  female  36.0   

     SibSp  Parch      Ticket      Fare    Cabin Embarked  
117      1      1     PP 9549   16.7000       G6        S  
303      0      0      315092    8.6625      NaN        S  
30       1      0  SC/AH 3085   26.0000      NaN        S  
202      1      0    PC 17757  227.5250  C62 C64        C  
59       0      0    PC 17608  262.3750      B61        C

In [58]:
#a summary of the nummerical features
train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [59]:
#a summary of the nonnummerical features
train.describe(include='O')

Name   Sex Ticket    Cabin Embarked
count                   891   891    891      204      889
unique                  891     2    681      147        3
top     Murdlin, Mr. Joseph  male   1601  B96 B98        S
freq                      1   577      7        4      644

In [60]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [61]:
train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [62]:
train.shape

(891, 12)

In [63]:
train['PassengerId'].nunique()

891

In [64]:
train['Survived'].unique()

array([0, 1])

In [66]:
np.sort(train['Pclass'].unique())

array([1, 2, 3])

In [67]:
train['Name'].nunique()

891

In [68]:
train['Sex'].unique()

array(['male', 'female'], dtype=object)

In [69]:
train['Age'].unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [70]:
train['SibSp'].unique()

array([1, 0, 3, 4, 2, 5, 8])

In [71]:
train['Age'].nunique()

88

In [72]:
train.groupby(['Age']).Age.count()

Age
0.42     1
0.67     1
0.75     2
0.83     2
0.92     1
        ..
70.00    2
70.50    1
71.00    2
74.00    1
80.00    1
Name: Age, Length: 88, dtype: int64

In [76]:
def unique_columns(dataframe, columns_list):
    
    for column in list(dataframe[columns_list]):
        x = dataframe[column].unique()
        if len(x) <10:
            print(column,x)

unique_columns(train,['Sex','Pclass'])

Sex ['male' 'female']
Pclass [3 1 2]


In [77]:
train['Age'][(train.Age==22) & (train.Sex=='female') & (train.Pclass==1)].count()

4